# fly.toml app configuration file generated for little-sound-4986 on 2023-11-08T15:52:30-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "little-sound-4986"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
